spring:
  banner:
    location: ${banner.location}
  application:
    name: recharge-service
  redis:
    database: 0
    host: 192.168.100.155
    port: 6379
    timeout: 600ms
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/smartcontact
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      repositories:
        enabled: false
datasource:
  master:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/smartcontact
    driver-class-name: com.mysql.cj.jdbc.Driver
  slave:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/smartcontact
    driver-class-name: com.mysql.cj.jdbc.Driver    

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${eurekaclient.uri}
    healthcheck:
      enabled: true 
      
      
      
             
