spring:
  banner:
    location: ${banner.location}
  application:
    name: recharge-service
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    database: mysql    
  datasource:
    type: com.zaxxer.hikari.HikariDataSource          

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${eurekaclient.uri}
    healthcheck:
      enabled: true        

      
      
      
             
